name: starter2
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  flutter_native_splash: ^2.2.16
  flutter_launcher_icons: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
#    - assets/audio/

# flutter pub run flutter_native_splash:create
flutter_native_splash: 
  color: "#000000"
  image: assets/images/splash_1024x477.png
  android: true
  ios: true

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon_432x432.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  
